Vagrant.configure("2") do |config|
    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/focal64"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip:"192.168.56.69"
    end
    config.vm.define "web02" do |web02|
        web02.vm.box = "ubuntu/focal64"
        web02.vm.hostname = "web01"
        web02.vm.network "private_network", ip:"192.168.56.70"
    end
    config.vm.define "db03" do |db03|
        db03.vm.box = "centos/7"
        db03.vm.hostname = "db03"
        db03.vm.network "private_network", ip:"192.168.56.71"
        db03.vm.provision "shell", inline: <<-SHELL
        yum install -y wget unzip mariadb-server -y
        systemctl start mariadb
        systemctl enable mariadb
        echo "========================="
        echo "INSTALLATION COMPLETED"
        echo "========================="
        SHELL
    end

  end
  